spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

cards:
  message: "Welcome to my world QA REST API's"
  contactDetails:
    name: "John Doe - QA LEAD"
    email: "gopi.thochi_q@gmail.com"
  onCallSupport:
    -(040)26728
    -(91)9945544440