services:

  accountsdb:
    image: mysql
    container_name: accountsdb
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: accountsdb
    networks:
      - eazybank

  loansdb:
    image: mysql
    container_name: loansdb
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loansdb
    networks:
      - eazybank

  cardsdb:
    image: mysql
    container_name: cardsdb
    ports:
      - 3308:3306
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loansdb
    networks:
      - eazybank

  configserver:
    image: "gopinathtoka/configserver:s6"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"
    networks:
      - eazybank

  accounts:
    image: "gopinathtoka/accounts:s7"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_completed_successfully
      accountsdb:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILE_ACTIVE: default
      SPRING_RABBITMQ_HOST: "rabbit"
      MYSQL_DATASOURCE_USERNAME: root
      MYSQL_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"

  loans:
    image: "gopinathtoka/loans:s7"
    container_name: loans-ms
    ports:
      - "8090:8090"
    depends_on:
      configserver:
        condition: service_completed_successfully
      loansdb:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILE_ACTIVE: default
      SPRING_RABBITMQ_HOST: "rabbit"
      MYSQL_DATASOURCE_USERNAME: root
      MYSQL_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3307/loansdb"

  cards:
    image: "gopinathtoka/cards:s7"
    container_name: cards-ms
    ports:
      - "9000:9000"
    depends_on:
      configserver:
        condition: service_completed_successfully
      cardsdb:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILE_ACTIVE: default
      SPRING_RABBITMQ_HOST: "rabbit"
      MYSQL_DATASOURCE_USERNAME: root
      MYSQL_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3308/cardsdb"

networks:
  eazybank:
    driver: "bridge"